services:
  - type: web
    name: banking-app-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://banking-app-2-eyu9.onrender.com